### ISSUE TITLE
crowd_human_face_train里面定义了person和face两个类别，但是在训练集中是没有face这个类别的，这样做的原因是什么呢

### ISSUE THREAD

**Issue by deep-practice** [CPFLAME/centerX#10]
对detectron不熟，看了很久没看明白，这些类别定义起到了什么作用？训练集没有标注的类别是怎么学习到的呢

**Comment by CPFLAME** [comment]
这个主要是为了跑一个对比试验，ignore_label的训练，在这个issue下有相关的回答~
[点这里](https://github.com/CPFLAME/centerX/issues/5#issuecomment-737740464)

**Comment by deep-practice** [comment]
在代码里面是体现在哪些文件里的呢？

**Comment by deep-practice** [comment]
defaults.py
