### ISSUE TITLE
有论文做详细介绍吗？

### ISSUE THREAD

**Issue by 5RJ** [CPFLAME/centerX#11]
作者，你好，感谢你的贡献。请问这份工程有对应的论文吗？可以po一下吗？我想基于你这个工程实践增量学习，你觉得可行吗？

**Comment by CPFLAME** [comment]
欢迎cite centerX，我觉得非常可行，但由于本人不喜欢写论文，所以暂时没有论文放出来
但是近期（1个月以内）会写一个简单版的arxiv发表出来

**Comment by 5RJ** [comment]
提前谢谢大佬！

**Comment by xiweiya** [comment]
你好，请问arxiv发表出来了吗，谢谢！

**Comment by CPFLAME** [comment]
@xiweiya  由于作者的拖延症和不想写论文，arxiv论文再次推迟了
