### ISSUE TITLE
The training curve is strange

### ISSUE THREAD

**Issue by iMurphL** [CPFLAME/centerX#12]
Hi~ Thank you for your sharing!
I trained three times with different categories in COCO with default configs. The AP curve always dropped suddenly in the middle, then slowly rise. It feels like retraining in the middle. Like this:
![image](https://user-images.githubusercontent.com/38401357/101790193-26818b80-3b3d-11eb-982c-3f2ba25562ca.png)
I checked most of the config params in the yaml files but did not find the reason. Could you tell me which config params made this happened?

**Comment by CPFLAME** [comment]
I have met this AP curve before， when I set smaller Base_lr，it will be fine.

**Comment by CPFLAME** [comment]
@iMurphL  
Hi, I found an operation in centernet. Maybe this can help.  

"For other pytorch version, you can manually open torch/nn/functional.py and find the line with torch.batch_norm and replace the torch.backends.cudnn.enabled with False. We observed slight worse training results without doing so."
