### ISSUE TITLE
您好，训练一定时间后出现错误assert len(class_names)==precisions.shape[2]，请问是哪里有问题呢

### ISSUE THREAD

**Issue by shashengtao** [CPFLAME/centerX#14]

**Comment by CPFLAME** [comment]
你应该用的是自己转好的coco格式的私库吧，
可能是 你私库里面的类别 和 你在builting里面注册的类别   不一样导致的？

**Comment by shashengtao** [comment]
> 你应该用的是自己转好的coco格式的私库吧，
> 可能是 你私库里面的类别 和 你在builting里面注册的类别 不一样导致的？

请问训练类别需要加一吗

**Comment by CPFLAME** [comment]
不需要加一

**Comment by shashengtao** [comment]
> 不需要加一

我是在训练的train_net.py里注册的数据集，类别个数也加一了
请问有训练个人数据集的教程吗

**Comment by CPFLAME** [comment]
centerX和detectron2里面的数据注册是一样的，你可以参考detectron2的官方教程https://detectron2.readthedocs.io/tutorials/builtin_datasets.html

你也可以借鉴一下centerX里面的其他数据集是怎么注册的，写一个数据集读取代码之后，再在builting.py里面注册一下好了
https://github.com/CPFLAME/centerX/tree/master/data/dataset

**Comment by kejuZhang** [comment]
遇到了同样的问题 请问楼主解决了吗？感谢分享
