### ISSUE TITLE
你好，请问您出了论文详述了嘛 & KD相关

### ISSUE THREAD

**Issue by xiweiya** [CPFLAME/centerX#19]
1. 作者你好，请问您出了论文详述了嘛，想学习一下。
2. 我resnet18单独训练模型大小为111M，但是KD之后（res50为teacher，res18为student），res18模型大小为166M，不跟原始的res18一致，模型参数量发生了变化，请问是这样吗？

**Comment by CPFLAME** [comment]
1.论文由于我的拖延症，和不想写论文的心里，被无限期延迟了 = =
2.模型的参数量应该是不变的，应该是pth里面存入了和模型无关的参数，可以尝试一下转onnx和转caffe，生成的model文件大小是最干净的。

**Comment by xiweiya** [comment]
嗯嗯，好的，谢谢。再请问一下，我看代码中好像没有续训练的选项，请问是这样的吗？

**Comment by CPFLAME** [comment]
我的代码中没有，但是detectron2本身包含这个功能，
印象中没有错的话，只需要在yaml里面指定一下续训练的weights，然后outputs不变，并在运行指令中加入--resume就可以了。
详情还是请看detectron2的官方说明文档。

如果要保存中间model 的话，可以在yamls中加入一下的字段
```
SOLVER:
    CHECKPOINT_PERIOD: 2 (每2个epoch数量保存一次模型，具体可以根据你的实际需求调整)
```

**Comment by xiweiya** [comment]
嗯嗯，好的，谢谢啦~
