### ISSUE TITLE
请问速度和推理时间相比yolov5如何？

### ISSUE THREAD

**Issue by Xiangyu-CAS** [CPFLAME/centerX#20]
您好，请问有推理时间相关的结论吗？譬如在V100/2080Ti上能到多少FPS, 和yolov5相比如何呢？

**Comment by CPFLAME** [comment]
时间推理在P40上  在coco上resdcn18单张图片从预处理，前向，后处理，大概在11ms左右，不过我的机器比较慢。在V100和2080Ti上应该能快不少。
V100和2080Ti的卡我没有，和yolov5不太好比，backbone不一样，而且据说yolov5是用batch的输入和dataloader去算的单张图片时间。在相同的backbone和同等的input size的情况下，应该是比yolov5略快的。

**Comment by Xiangyu-CAS** [comment]
@CPFLAME 谢谢！
