### ISSUE TITLE
数据存放位置

### ISSUE THREAD

**Issue by huanpig** [CPFLAME/centerX#22]
你好，我想用coco数据集训练一下，请问coco文件夹放在哪里啊

**Comment by CPFLAME** [comment]
把项目里面的datasets删掉，然后新建一个datasets文件夹
然后把coco文件夹放在datasets文件夹下面就可以了

**Comment by huanpig** [comment]
还有一个问题，就是，在centertrainer类里面，有个super（DefaultTrainer，self）.__init__(model,data_loader, optimizer)
出现错误，
__init__() take 1 positional argument but 4 were given
我想确定一下，一般出现这种问题，这个程序真的能直接跑吗？

**Comment by huanpig** [comment]
@CPFLAME

**Comment by CPFLAME** [comment]
应该是你装的detectron2版本不对，可以根据readme里面的提示安装：
pip install -U 'git+https://github.com/CPFLAME/detectron2.git'

其他的issue也出现了类似的问题，但是也有热心人士解答。你和这个道友遇到的问题一样[点这里](https://github.com/JDAI-CV/centerX/issues/13#issuecomment-747231537)

**Comment by huanpig** [comment]
我是按照官方安装的detectron2，你的意思是通过你这个命令安装是吧？ @CPFLAME

**Comment by CPFLAME** [comment]
是的

**Comment by huanpig** [comment]
谢谢回答。但是我这显示用你的安装后，from detectreon2 import _C,显示缺少libcudart.so.9.0，这说明你的程序改了后是只能在cuda9.0下跑吗？ @CPFLAME

**Comment by CPFLAME** [comment]
我程序改的只是流程和网络，整个架构基本没有变，和对应版本的detectron2要求应该不会冲突，不至于改了就不支持本来就支持的cuda版本了。
也许这个可以帮助到你 [issue](https://github.com/JDAI-CV/centerX/issues/17#issuecomment-749544215)

by the way： 听你的表达很容易血压飙升，你的话可以一击命中程序员的恼怒点
“这个程序真的能直接跑吗”
“这说明你的程序改了后是只能在cuda9.0下跑吗？”

我捂着心脏平复了好一会儿才心态平稳的回复这条issue。

**Comment by huanpig** [comment]
你好，还有个问题，我看到yaml里面有个max_iter设置的是70，但是我看到detectron2里面一般是比较大的数，应该是iter，请问你这里是修改成了epoch吗，才设置成这样？ @CPFLAME

**Comment by CPFLAME** [comment]
是的，就是epoch数目
在代码块中[engine/defaults.py](https://github.com/JDAI-CV/centerX/blob/1073753533f26483c3ab053a7d8753708fcacde7/engine/defaults.py#L357)我做了一个变换
主要是为了解放使用者的脑力，不用自己手动去算iter数量了
