### ISSUE TITLE
小数据集训练问题

### ISSUE THREAD

**Issue by XiaoCode-er** [CPFLAME/centerX#23]
你好，
我在训练自己的小数据集上遇到了问题，
我先是用CenterX在coco数据集上，复现了你的res18和res50实验结果。
换成自己的小数据集后，在原始的Centernet上代码上的AP大约在0.59左右；但是在CenterX上经过多次尝试（例如调整学习率方式，数据增强等），AP最好的时候大约只有0.49左右。我这分析觉得可能是数据增强的方式不太对。
我看了一下你对比实验中一项是数据增强的结果比原始的结果要略低一点，对于这个问题你有什么想法或者建议吗？

**Comment by CPFLAME** [comment]
非常感谢你的反馈，
对于私库我也没有什么比较好的办法，不过一般影响detection的测试性能的坑就是：测试图片大小，数据预处理如减均值除方差等是否和训练一样，以及测试指标的code是否一致。
可以先人眼看看两者的输出在原图上是否有很大的差距，来排除测试指标code不一致的问题，
然后检查一下各自的测试图片大小和数据预处理有没有bug，来排除测试时候的问题。
如果都没有问题，那可能就是训练时候出了问题，对于比较小的数据集的话，任何一个超参对结果的影响可能都比较大，得仔细排查一下。比如小数据集是否锁住BN的统计量，学习率，batch size，数据增强方式等。

再加一个我在centernet里面看到的建议, 貌似可以解决centerX训练的时候mAP骤降的问题
"For other pytorch version, you can manually open torch/nn/functional.py and find the line with torch.batch_norm and replace the torch.backends.cudnn.enabled with False. We observed slight worse training results without doing so.
"

**Comment by XiaoCode-er** [comment]
@CPFLAME 谢谢哈，参照你的建议，问题已解决，多个模型教小模型的流程也跑通了。
再请教两个问题哈，
1. 在centernet中图像都是缩放然后padding成512x512的，但centerX中每个batch的图像长边是固定为512，短边是不同的，这样做操作可以理解为数据增强嘛？
2. 在centerX中没有固定随机种子嘛？每次训练的结果都不太一样呀。

**Comment by CPFLAME** [comment]
@XiaoCode-er 非常感谢你的回复，可以分享一下问题出在哪里么？
下面对两个问题进行解答
1.centerX中的是直接复用的detectron2的数据处理，不能算作数据增强，只是一种数据预处理的方式罢了，另外长边并不一定是固定512，而是最长的边不会超过512，具体可以看detectron2中的ResizeShortestEdge函数。
2.我在centerX里面并没有固定随机数种子，如果需要的时候可以自行在主函数里面设置一下

**Comment by XiaoCode-er** [comment]
@CPFLAME 一开始我是按照你的centernet_res18_coco.yaml去配置的，因为在coco运行的时候指标测试都是正常的，所以就直接改了DATASETS部分的配置，在自己的小数据集上测试时指标比较差，一直以为是训练过程有问题。后来在你回复后感觉可能是测试输入的问题，就看了一下INPUT.MIN_SIZE_TEST: 0，觉得有些奇怪所以就把MIN_SIZE_TEST和MAX_SIZE_TEST改成512后，测试指标就上去了。
最近忙着赶紧把流程跑完，所以很多参数都没细看，对detectron2的数据处理挺迷惑的，不太明白这样处理的好处在哪里？而且MIN_SIZE_TEST、MAX_SIZE_TEST、MIN_SIZE_TRAIN、MAX_SIZE_TRAIN，一直没搞明白，我看你有些配置文件中是多个值，有些只有一个值，可能需要仔细看一下ResizeShortestEdge函数。
这两天会在centerX再做一些改动，有些问题可能还需请教一下你，还请多多指教。

**Comment by XiaoCode-er** [comment]
@CPFLAME 你好，我这边遇到一个问题，在训练多个模型教一个模型的时候，我对教师模型输出的结果进行了调整，一开始训练的损失是正常下降的，测试的AP也是正常上升的，迭代十几个epoch后，损失突然上升，AP骤降接近于0，然后继续训练损失没有任何变化。这个可能是什么原因导致的呀？

**Comment by CPFLAME** [comment]
@XiaoCode-er 请问你是如何进行调整的教师模型输出？
以及用这个可以尝试一下
“"For other pytorch version, you can manually open torch/nn/functional.py and find the line with torch.batch_norm and replace the torch.backends.cudnn.enabled with False. We observed slight worse training results without doing so.
"”

**Comment by XiaoCode-er** [comment]
@CPFLAME 将学习率降低后，这个问题也解决了。再请教一个问题哈，在cls分支经过sigmiod数值应该都为正数了，为什么在kd的时候还要再经过一次relu？还有在根据teacher的cls成wh_mask的时候使用的是leakyrelu？

**Comment by CPFLAME** [comment]
这个relu和leakyrelu是做实验的时候历史遗留问题，属于重复操作，其实并没有什么用。忽略它就好了
