### ISSUE TITLE
复现实验

### ISSUE THREAD

**Issue by TheUgliestOfWuli** [CPFLAME/centerX#26]
直接使用您的配置进行训练，widerface res50 精度为mAP24.1， res18的mAP为21.6，只修改了batchsize 从64改为16, 效果会差这么多么？ 另外 KD训练RES50 -> RES18 时 训练中期，kd_cls_loss 上升，可能是什么原因（BS=16）。

**Comment by CPFLAME** [comment]
修改batchsize后
一般LR得同比的调小

**Comment by TheUgliestOfWuli** [comment]
OJBK， 我试试，你这回复速度 可以的

**Comment by TheUgliestOfWuli** [comment]
哈喽，请问您这边的数据是用了widerface和mafa数据一起训练的吗？

**Comment by CPFLAME** [comment]
对的
