### ISSUE TITLE
Could you please release COCO pretrained model?

### ISSUE THREAD

**Issue by wanxinzzz** [CPFLAME/centerX#29]
Hello, thx for your great work! I'm trying to use this repo in my project, but it is hard to converge and cost much more time.Could you plz release coco pretrained model. Thx a lot ❤!

**Comment by CPFLAME** [comment]
I'm sorry that I cannot upload model due to company regulation.

But you can send me an email 410070869@qq.com.  : )
which model do you want?  resnet18 or resnet50?  w/wo dcn? Show me the details in your email.
