### ISSUE TITLE
Error in training a model based on RegNet

### ISSUE THREAD

**Issue by Fly-dream12** [CPFLAME/centerX#35]
训练RegNetX_400MF模型的时候, 下载了权重报如下错误:
  File "centerX-master/modeling/backbone/regnet/regnet.py", line 539, in init_pretrained_weights
    state_dict = torch.load(cached_file, map_location=torch.device('cpu'))['model_state']
  File "anaconda3/envs/yolov3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "anaconda3/envs/yolov3/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
请问是什么问题呢?

**Comment by CPFLAME** [comment]
你是下载的哪个权重呀？
下载这个权重应该没有问题https://github.com/facebookresearch/pycls/blob/master/MODEL_ZOO.md

**Comment by Fly-dream12** [comment]
程序里面是按照这个直接下载的哇 in modeling/backbone/regnet/regnet.py
model_urls = '400x': 'https://dl.fbaipublicfiles.com/pycls/dds_baselines/160906036/RegNetX-400MF_dds_8gpu.pyth'



在 2021-05-17 16:25:28，"CPFLAME" ***@***.***> 写道：

你是下载的哪个权重呀？
下载这个权重应该没有问题https://github.com/facebookresearch/pycls/blob/master/MODEL_ZOO.md

**Comment by CPFLAME** [comment]
这个链接好像失效了  我这边下不下来， 你用我发的链接里面的model试试呢

**Comment by Fly-dream12** [comment]
可以了,另外想问下博主这个项目可以做特征蒸馏吗, 尝试了一下效果反而变差了,有什么建议吗?



在 2021-05-17 18:47:06，"CPFLAME" ***@***.***> 写道：

这个链接好像失效了 我这边下不下来， 你用我发的链接里面的model试试呢

**Comment by CPFLAME** [comment]
特征蒸馏我自己也尝试了一些，也加入了overhaul尝试了一下。
但不知道是我实验配置可能不太好，最后的结果都比不上用最后预测的logits直接蒸，而且用特征蒸馏也丧失了多模型蒸馏的优点，所以我个人还是更倾向用预测的logits蒸馏。

**Comment by Fly-dream12** [comment]
这里说的多模型蒸馏 是针对那种组合数据集吗 最后达到同时检测两类目标的效果?



在 2021-05-18 11:31:38，"CPFLAME" ***@***.***> 写道：

特征蒸馏我自己也尝试了一些，也加入了overhaul尝试了一下。
但不知道是我实验配置可能不太好，最后的结果都比不上用最后预测的logits直接蒸，而且用特征蒸馏也丧失了多模型蒸馏的优点，所以我个人还是更倾向用预测的logits蒸馏。

**Comment by CPFLAME** [comment]
对，是的
