### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 4 were given

### ISSUE THREAD

**Issue by starsky68** [CPFLAME/centerX#40]
File "/home/ac/code/centerX-master/engine/defaults.py", line 71, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given

**Comment by CPFLAME** [comment]
Refer to https://github.com/JDAI-CV/centerX/issues/17#issue-772594795
