### ISSUE TITLE
TypeError: _write_metrics() missing 1 required positional argument: 'data_time'

### ISSUE THREAD

**Issue by starsky68** [CPFLAME/centerX#41]
File "/home/a/.local/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 133, in train
    self.run_step()
  File "/home/a/code/centerX-master/engine/defaults.py", line 353, in run_step
    self._write_metrics(metrics_dict)
TypeError: _write_metrics() missing 1 required positional argument: 'data_time'

**Comment by CPFLAME** [comment]
Maybe the your detectron2 version is not match.
refer to https://github.com/JDAI-CV/centerX/issues/17#issue-772594795

**Comment by starsky68** [comment]
> Maybe the your detectron2 version is not match.
> refer to [#17 (comment)](https://github.com/JDAI-CV/centerX/issues/17#issue-772594795)

学习率每设置好，导致FloatingPointError: Loss became infinite or NaN at iteration=227!，进而导致了这个错误。
