### ISSUE TITLE
转caffe遇到问题

### ISSUE THREAD

**Issue by starsky68** [CPFLAME/centerX#43]
File "./modeling/layers/centernet_deconv.py", line 91, in forward
    offset = torch.cat((o1, o2), dim=1)
  File "/home/22/code/centerX-master/projects/speedup/pytorch_to_caffe.py", line 660, in __call__
    out = self.obj(self.raw, *args, **kwargs)
TypeError: _cat() got an unexpected keyword argument 'dim'

配置文件和模型是匹配的，为何还会出现这个问题

**Comment by CPFLAME** [comment]
看上去你用了deformable conv，这个层要转码特别的麻烦，不建议转码时使用改层，建议直接换成普通的卷积。
refer to https://github.com/JDAI-CV/centerX/issues/36#issuecomment-842125288

**Comment by starsky68** [comment]
> 看上去你用了deformable conv，这个层要转码特别的麻烦，不建议转码时使用改层，建议直接换成普通的卷积。
> refer to [#36 (comment)](https://github.com/JDAI-CV/centerX/issues/36#issuecomment-842125288)

好的，谢谢回复。
