### ISSUE TITLE
wider_face_add_lm_10_10_add_mafa

### ISSUE THREAD

**Issue by deep-practice** [CPFLAME/centerX#5]
what't 'add_mafa' mean?

**Comment by CPFLAME** [comment]
It's a face dataset MAFA（A Dataset of MAsked FAces),
I just add it to wider face dataset

**Comment by deep-practice** [comment]
Can you share the download link?I can't find this dataset in its official website.

**Comment by CPFLAME** [comment]
Sorry I can't, cause I copy it from my friends🤣

**Comment by deep-practice** [comment]
widerface_crowdhuman_train and  face_train is the same dataset in register_all_face  function?

**Comment by CPFLAME** [comment]
the data is the same while the classes is not the same.
widerface_crowdhuman_train has "person" and "face" class, but "person" annotation is null, it is used for ignore_unlabel training

**Comment by deep-practice** [comment]
Got it.
