### ISSUE TITLE
 CUDA out of memory. 1080Ti 11G  how can i less the memory ?

### ISSUE THREAD

**Issue by lightingstars** [CPFLAME/centerX#6]

**Comment by lightingstars** [comment]
both train and test , both all out of memory

**Comment by CPFLAME** [comment]
you can set the IMS_PER_BATCH smaller in yaml, 
and change BASE_LR linearly according to your modification

**Comment by lightingstars** [comment]
> BASE_LR

thank you very much
do you mean that if i  change IMS_PER_BATCH 64 to 16
then BASE_LR should change from 0.2 to 0.05

**Comment by CPFLAME** [comment]
yes！
Absolutely right！

**Comment by lightingstars** [comment]
> yes！
> Absolutely right！

thank you very much
have a good day!
