### ISSUE TITLE
作者你好，我想问一下你在kd_loss里面定义的kd_parameter是什么呢，我看是从detectron2导入的，然后我去看了下detectron2的代码，发现导入的那部分是一些打开配置等的一些函数。这地方我不太明白那个参数是什么，可以解释一下吗？

### ISSUE THREAD

**Issue by 18804601171** [CPFLAME/centerX#9]

**Comment by CPFLAME** [comment]
_C.MODEL.CENTERNET.KD = CN()
    _C.MODEL.CENTERNET.KD.ENABLED = False    #是否使用蒸馏
    _C.MODEL.CENTERNET.KD.TEACHER_CFG = ["None", ]   # teacher model的yaml
    _C.MODEL.CENTERNET.KD.TEACHER_WEIGTHS = ["None", ] # teacher model 的权重
    _C.MODEL.CENTERNET.KD.KD_WEIGHT = [10.0, ]  # KD loss的总权重
    _C.MODEL.CENTERNET.KD.KD_CLS_WEIGHT = [1.0, ] # KD loss的cls分支权重
    _C.MODEL.CENTERNET.KD.KD_WH_WEIGHT = [1.0, ] # KD loss的wh分支权重
    _C.MODEL.CENTERNET.KD.KD_REG_WEIGHT = [0.1, ] # KD loss的offset分支权重
    _C.MODEL.CENTERNET.KD.KD_CLS_INDEX = [1, ] # 蒸馏的cls部分的索引值，比如teacher1有3类，teacher2有4类，两个共同蒸馏同一个student时，赋值为[3,7]，指的是student的cls channel分别取[0:3]以及[3:7]
    _C.MODEL.CENTERNET.KD.NORM_WH = [False, ] # 蒸馏时wh分支是否norm
    _C.MODEL.CENTERNET.KD.KD_WITHOUT_LABEL = False #蒸馏时是否 不使用label作为监督（只用KD loss）

**Comment by 18804601171** [comment]
@CPFLAME 那个CN（）是什么呢？

**Comment by CPFLAME** [comment]
好家伙，你挑了个最不重要的问了😹
那个是detectron2里面自定义添加config字段的一种方式

**Comment by 18804601171** [comment]
@CPFLAME 那如果自己用的话，这个是不是可以不用呀，直接定义下面那些变量就好了

**Comment by CPFLAME** [comment]
没太清楚要表达的意思，自己是要怎么用呢？

**Comment by 18804601171** [comment]
@CPFLAME 就是我想在自己的代码里用一下这个蒸馏，我这个代码也是基于cnternet改的，但是这个工程基于detectron2的一些东西我不太明白😂

**Comment by CPFLAME** [comment]
那你可以参考 [centernet_kdloss.py](https://github.com/CPFLAME/centerX/blob/master/modeling/losses/centernet_kdloss.py) 自行添加~

**Comment by 18804601171** [comment]
@CPFLAME 好的，我先试试看

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我想问一下kdloss.py里有个output['mask_cls']是什么呢

**Comment by CPFLAME** [comment]
那个是用来生成 蒸馏wh分支的权重

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我想问一下，在进行蒸馏的时候，蒸馏损失需要和三个head的损失相加吗

**Comment by CPFLAME** [comment]
在有标签的蒸馏中是需要相加的。
在无标签的蒸馏中，网络只有蒸馏的损失，所以不需要相加

**Comment by 18804601171** [comment]
@大佬，我想问一下，就是分支用什么损失函数是如何确定的呢

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我想问一下每个分支用什么损失函数是怎么确定的呢？

**Comment by 18804601171** [comment]
@CPFLAME 大佬，请问蒸馏分支的时候，每个损失的权重怎么确定的呢，是做实验调的嘛

**Comment by CPFLAME** [comment]
是的  是根据正常训练的loss   手动调到  相同的量级

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我没理解错的话，就是调权重，使得最后加了蒸馏损失的loss和没有加蒸馏损失的loss接近，是这个意思吗

**Comment by CPFLAME** [comment]
对 是的， 企业级理解

**Comment by 18804601171** [comment]
@CPFLAME 谢谢大佬指导，哈哈

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我想知道什么情况下用MSEloss，什么时候用L1loss呢

**Comment by CPFLAME** [comment]
@18804601171  MSEloss在蒸馏的时候用于在cls分支上（拍脑袋想的），L1loss在蒸馏的时候用于在wh和off的分支上（这两个分支保持loss和原文的方法一致）。

**Comment by zzyx1215** [comment]
> _No description provided._

你好，我也是想在别的一个基于centernet算法中使用一下该蒸馏方法，请问下你是怎样做的呢，需要改动哪些呢

**Comment by zzyx1215** [comment]
> @CPFLAME 大佬，请问蒸馏分支的时候，每个损失的权重怎么确定的呢，是做实验调的嘛



> @CPFLAME 就是我想在自己的代码里用一下这个蒸馏，我这个代码也是基于cnternet改的，但是这个工程基于detectron2的一些东西我不太明白😂

你好，我也是想在别的一个基于centernet算法中使用一下该蒸馏方法，请问下你是怎样做的呢，需要改动哪些呢

**Comment by 18804601171** [comment]
@CPFLAME 大佬，我想问一下，预测分支的通道数已知，为什么还要用那个类别索引呢？

**Comment by CPFLAME** [comment]
@zzyx1215 可以参考[centernet_kdloss.py](https://github.com/JDAI-CV/centerX/blob/master/modeling/losses/centernet_kdloss.py)

**Comment by CPFLAME** [comment]
@18804601171 类别索引是为了方便多teacher蒸馏，可以在yaml里面指定 学生网络的特定通道用来学习teacherN的分类输出。
